package rules

import model.Pacijent;
import model.KKS;
import model.KKSVrednosti;
import enums.Kolicina;
import model.EnzimiUKrvi;
import model.EnzimiUKrviVrednosti;

rule "Zensko,ckMb,normalno"
agenda-group "enzimiKrvi"
    when
    $p: Pacijent(zensko==true) and
        $ek: EnzimiUKrvi( ckMb < 2.88) and
        $ekVrednost: EnzimiUKrviVrednosti (ckMb==Kolicina.NA)
    then
        $ekVrednost.setCkMb(Kolicina.NORMALNO);
        update($ekVrednost);
end

rule "Zensko,ckMb,visoko"
agenda-group "enzimiKrvi"
    when
    $p: Pacijent(zensko==true) and
        $ek: EnzimiUKrvi( ckMb >=2.88 ) and
        $ekVrednost: EnzimiUKrviVrednosti (ckMb==Kolicina.NA)
    then
        $ekVrednost.setCkMb(Kolicina.VISOKO);
        update($ekVrednost);
end


