package rules

import model.Pacijent;
import model.KKS;
import model.KKSVrednosti;
import enums.Kolicina;

rule "Musko,eritrociti,nisko"
agenda-group "kks"
    when
    	$p: Pacijent(zensko==false) and
        $kks: KKS( eritrociti < 4.34 ) and
        $kksVrednost: KKSVrednosti (eritrociti==Kolicina.NA)
    then
        $kksVrednost.setEritrociti(Kolicina.NISKO);
        update($kksVrednost);
end

rule "Musko,eritrociti,visoko"
agenda-group "kks"
    when
    	$p: Pacijent(zensko==false) and
        $kks: KKS( eritrociti > 5.72 ) and
        $kksVrednost: KKSVrednosti (eritrociti==Kolicina.NA)
    then
        $kksVrednost.setEritrociti(Kolicina.VISOKO);
        update($kksVrednost);
end

rule "Musko,eritrociti,normalno"
agenda-group "kks"
    when
    	$p: Pacijent(zensko==false) and
        $kks: KKS( eritrociti >= 4.34 && eritrociti<=5.72 ) and
        $kksVrednost: KKSVrednosti (eritrociti==Kolicina.NA)
    then
        $kksVrednost.setEritrociti(Kolicina.NORMALNO);
        update($kksVrednost);
end
