package rules

import model.Pacijent;
import model.KKS;
import model.KKSVrednosti;
import enums.Kolicina;

rule "Zensko,kreatinin,nisko"
agenda-group "kks"
    when
    	$p: Pacijent(zensko==true) and
        $kks: KKS( kreatinin < 44 ) and
        $kksVrednost: KKSVrednosti (kreatinin==Kolicina.NA)
    then
        $kksVrednost.setKreatinin(Kolicina.NISKO);
        update($kksVrednost);
end

rule "Zensko,kreatinin,visoko"
agenda-group "kks"
    when
    	$p: Pacijent(zensko==true) and
        $kks: KKS( kreatinin > 80 ) and
        $kksVrednost: KKSVrednosti (kreatinin==Kolicina.NA)
    then
        $kksVrednost.setKreatinin(Kolicina.VISOKO);
        update($kksVrednost);
end

rule "Zensko,kreatinin,normalno"
agenda-group "kks"
    when
    	$p: Pacijent(zensko==true) and
        $kks: KKS( kreatinin >= 40 && kreatinin<=80 ) and
        $kksVrednost: KKSVrednosti (kreatinin==Kolicina.NA)
    then
        $kksVrednost.setKreatinin(Kolicina.NORMALNO);
        update($kksVrednost);
end
