package rules

import model.Pacijent;
import model.KKS;
import model.KKSVrednosti;
import enums.Kolicina;

rule "lym,nisko"
agenda-group "kks"
    when
        $kks: KKS( lym < 20 ) and
        $kksVrednost: KKSVrednosti (lym==Kolicina.NA)
    then
        $kksVrednost.setLym(Kolicina.NISKO);
        update($kksVrednost);
end

rule "lym,visoko"
agenda-group "kks"
    when
        $kks: KKS( lym > 50 ) and
        $kksVrednost: KKSVrednosti (lym==Kolicina.NA)
    then
        $kksVrednost.setLym(Kolicina.VISOKO);
        update($kksVrednost);
end

rule "lym,normalno"
agenda-group "kks"
    when
        $kks: KKS( lym >= 20 && lym<=50 ) and
        $kksVrednost: KKSVrednosti (lym==Kolicina.NA)
    then
        $kksVrednost.setLym(Kolicina.NORMALNO);
        update($kksVrednost);
end
