package rules

import model.Pacijent;
import model.KKS;
import model.KKSVrednosti;
import enums.Kolicina;

rule "mcv,nisko"
agenda-group "kks"
    when
        $kks: KKS( mcv < 85 ) and
        $kksVrednost: KKSVrednosti (mcv==Kolicina.NA)
    then
        $kksVrednost.setMcv(Kolicina.NISKO);
        update($kksVrednost);
end

rule "mcv,visoko"
agenda-group "kks"
    when
        $kks: KKS( mcv > 100 ) and
        $kksVrednost: KKSVrednosti (mcv==Kolicina.NA)
    then
        $kksVrednost.setMcv(Kolicina.VISOKO);
        update($kksVrednost);
end

rule "mcv,normalno"
agenda-group "kks"
    when
        $kks: KKS( mcv >= 85 && mcv<=100 ) and
        $kksVrednost: KKSVrednosti (mcv==Kolicina.NA)
    then
        $kksVrednost.setMcv(Kolicina.NORMALNO);
        update($kksVrednost);
end
