package rules

import model.Pacijent;
import model.KKS;
import model.KKSVrednosti;
import enums.Kolicina;
import model.EnzimiUKrvi;
import model.EnzimiUKrviVrednosti;

rule "Musko,mioglobin,nisko"
agenda-group "enzimiKrvi"
    when
    $p: Pacijent(zensko==false) and
        $ek: EnzimiUKrvi( mioglobin < 17) and
        $ekVrednost: EnzimiUKrviVrednosti (mioglobin==Kolicina.NA)
    then
        $ekVrednost.setMioglobin(Kolicina.NISKO);
        update($ekVrednost);
end

rule "Musko,mioglobin,visoko"
agenda-group "enzimiKrvi"
    when
    $p: Pacijent(zensko==false) and
        $ek: EnzimiUKrvi( mioglobin >106 ) and
        $ekVrednost: EnzimiUKrviVrednosti (mioglobin==Kolicina.NA)
    then
        $ekVrednost.setMioglobin(Kolicina.VISOKO);
        update($ekVrednost);
end

rule "Musko,mioglobin,normalno"
agenda-group "enzimiKrvi"
    when
    $p: Pacijent(zensko==false) and
        $ek: EnzimiUKrvi( mioglobin >= 17 && mioglobin<=106 ) and
        $ekVrednost:EnzimiUKrviVrednosti (mioglobin==Kolicina.NA)
    then
        $ekVrednost.setMioglobin(Kolicina.NORMALNO);
        update($ekVrednost);
end


