package rules

import model.Pacijent;
import model.KKS;
import model.KKSVrednosti;
import enums.Kolicina;

rule "neu,nisko"
agenda-group "kks"
    when
        $kks: KKS( neu < 40 ) and
        $kksVrednost: KKSVrednosti (neu==Kolicina.NA)
    then
        $kksVrednost.setNeu(Kolicina.NISKO);
        update($kksVrednost);
end

rule "neu,visoko"
agenda-group "kks"
    when
        $kks: KKS( neu > 70 ) and
        $kksVrednost: KKSVrednosti (neu==Kolicina.NA)
    then
        $kksVrednost.setNeu(Kolicina.VISOKO);
        update($kksVrednost);
end

rule "neu,normalno"
agenda-group "kks"
    when
        $kks: KKS( neu >= 40 && neu<=70 ) and
        $kksVrednost: KKSVrednosti (neu==Kolicina.NA)
    then
        $kksVrednost.setNeu(Kolicina.NORMALNO);
        update($kksVrednost);
end
