package rules

import model.Pacijent;
import model.KKS;
import model.KKSVrednosti;
import enums.Kolicina;
import model.StitnaZlezda;
import model.StitnaZlezdaVrednosti;

rule "t3,nisko"
agenda-group "stitna"
    when
        $sz: StitnaZlezda( t3 < 1.3) and
        $szVrednost: StitnaZlezdaVrednosti (t3==Kolicina.NA)
    then
        $szVrednost.setT3(Kolicina.NISKO);
        update($szVrednost);
end

rule "t3,visoko"
agenda-group "stitna"
    when
        $sz: StitnaZlezda( t3 >3.1 ) and
        $szVrednost: StitnaZlezdaVrednosti (t3==Kolicina.NA)
    then
        $szVrednost.setT3(Kolicina.VISOKO);
        update($szVrednost);
end

rule "t3,normalno"
agenda-group "stitna"
    when
        $sz: StitnaZlezda( t3 >= 1.3 && t3<=3.1 ) and
        $szVrednost: StitnaZlezdaVrednosti (t3==Kolicina.NA)
    then
        $szVrednost.setT3(Kolicina.NORMALNO);
        update($szVrednost);
end



