package rules

import model.Pacijent;
import model.KKS;
import model.KKSVrednosti;
import enums.Kolicina;
import model.DodatnoAnemija1;
import model.DodatnoAnemija1Vrednosti;

rule "Musko,tibc,nisko"
agenda-group "kks"
    when
    	$p: Pacijent(zensko==false) and
        $da: DodatnoAnemija1( tibc < 49 ) and
        $daVrednost: DodatnoAnemija1Vrednosti (tibc==Kolicina.NA)
    then
        $daVrednost.setTibc(Kolicina.NISKO);
        update($daVrednost);
end

rule "Musko,tibc,visoko"
agenda-group "kks"
    when
    	$p: Pacijent(zensko==false) and
        $da: DodatnoAnemija1( tibc > 72 ) and
        $daVrednost: DodatnoAnemija1Vrednosti (tibc==Kolicina.NA)
    then
        $daVrednost.setTibc(Kolicina.VISOKO);
        update($daVrednost);
end

rule "Musko,tibc,normalno"
agenda-group "kks"
    when
    	$p: Pacijent(zensko==false) and
        $da: DodatnoAnemija1( tibc >= 49 && tibc<=72 ) and
        $daVrednost: DodatnoAnemija1Vrednosti (tibc==Kolicina.NA)
    then
        $daVrednost.setTibc(Kolicina.NORMALNO);
        update($daVrednost);
end