package rules

import model.Pacijent;
import model.KKS;
import model.KKSVrednosti;
import enums.Kolicina;
import model.DodatnoAnemija1;
import model.DodatnoAnemija1Vrednosti;

rule "Musko,uibc,nisko"
agenda-group "kks"
    when
    	$p: Pacijent(zensko==false) and
        $da: DodatnoAnemija1( uibc <25 ) and
        $daVrednost: DodatnoAnemija1Vrednosti (uibc==Kolicina.NA)
    then
        $daVrednost.setUibc(Kolicina.NISKO);
        update($daVrednost);
end

rule "Musko,uibc,visoko"
agenda-group "kks"
    when
    	$p: Pacijent(zensko==false) and
        $da: DodatnoAnemija1( uibc > 54 ) and
        $daVrednost: DodatnoAnemija1Vrednosti (uibc==Kolicina.NA)
    then
        $daVrednost.setUibc(Kolicina.VISOKO);
        update($daVrednost);
end

rule "Musko,uibc,normalno"
agenda-group "kks"
    when
    	$p: Pacijent(zensko==false) and
        $da: DodatnoAnemija1( uibc >= 25 && uibc<=54 ) and
        $daVrednost: DodatnoAnemija1Vrednosti (uibc==Kolicina.NA)
    then
        $daVrednost.setUibc(Kolicina.NORMALNO);
        update($daVrednost);
end