package enums;

public enum Bolesti {
	ANEMIJA, SIDEROPENIJSKA_ANEMIJA, MEGALOBLASTNA_ANEMIJA, SIDEROBLASTNA_ANEMIJA, BAKTERIJSKO_ZAPALJENJE,
	VIRUSNO_ZAPALJENJE, INFEKCIJE, PANCITOPENIJA, BUBREZI, JETRA, ZUCNI_PUTEVI, ADENOHIPOFIZA, HIPERTIREOZA,
	PANKREATITIS, INFARKT_MIOKARDA, LEUKEMIJA
}
